#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatasetDesignerTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="jamming")]
	public partial class jammingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public jammingDataContext() : 
				base(global::DatasetDesignerTest.Properties.Settings.Default.jammingConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public jammingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public jammingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public jammingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public jammingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FREQ_TYPE> FREQ_TYPEs
		{
			get
			{
				return this.GetTable<FREQ_TYPE>();
			}
		}
		
		public System.Data.Linq.Table<JAM_TYPE> JAM_TYPEs
		{
			get
			{
				return this.GetTable<JAM_TYPE>();
			}
		}
		
		public System.Data.Linq.Table<PA_POWER> PA_POWERs
		{
			get
			{
				return this.GetTable<PA_POWER>();
			}
		}
		
		public System.Data.Linq.Table<RULE_DIGITAL> RULE_DIGITALs
		{
			get
			{
				return this.GetTable<RULE_DIGITAL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FREQ_TYPE")]
	public partial class FREQ_TYPE
	{
		
		private int _TYPE;
		
		private string _DESCRIPTION;
		
		public FREQ_TYPE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="Int NOT NULL")]
		public int TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this._DESCRIPTION = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JAM_TYPE")]
	public partial class JAM_TYPE
	{
		
		private int _MODE;
		
		private string _DESCRIPTION;
		
		public JAM_TYPE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODE", DbType="Int NOT NULL")]
		public int MODE
		{
			get
			{
				return this._MODE;
			}
			set
			{
				if ((this._MODE != value))
				{
					this._MODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this._DESCRIPTION = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PA_POWER")]
	public partial class PA_POWER
	{
		
		private int _POWER;
		
		private string _DESCRIPTION;
		
		public PA_POWER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POWER", DbType="Int NOT NULL")]
		public int POWER
		{
			get
			{
				return this._POWER;
			}
			set
			{
				if ((this._POWER != value))
				{
					this._POWER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this._DESCRIPTION = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RULE_DIGITAL")]
	public partial class RULE_DIGITAL
	{
		
		private System.Guid _ID;
		
		private int _JAM_MODE;
		
		private int _FREQ_TYPE;
		
		private long _FREQ1_HZ;
		
		private long _FREQ2_HZ;
		
		private byte _SPEED;
		
		private string _TELEGRAM;
		
		private int _POWER;
		
		public RULE_DIGITAL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JAM_MODE", DbType="Int NOT NULL")]
		public int JAM_MODE
		{
			get
			{
				return this._JAM_MODE;
			}
			set
			{
				if ((this._JAM_MODE != value))
				{
					this._JAM_MODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FREQ_TYPE", DbType="Int NOT NULL")]
		public int FREQ_TYPE
		{
			get
			{
				return this._FREQ_TYPE;
			}
			set
			{
				if ((this._FREQ_TYPE != value))
				{
					this._FREQ_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FREQ1_HZ", DbType="BigInt NOT NULL")]
		public long FREQ1_HZ
		{
			get
			{
				return this._FREQ1_HZ;
			}
			set
			{
				if ((this._FREQ1_HZ != value))
				{
					this._FREQ1_HZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FREQ2_HZ", DbType="BigInt NOT NULL")]
		public long FREQ2_HZ
		{
			get
			{
				return this._FREQ2_HZ;
			}
			set
			{
				if ((this._FREQ2_HZ != value))
				{
					this._FREQ2_HZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPEED", DbType="TinyInt NOT NULL")]
		public byte SPEED
		{
			get
			{
				return this._SPEED;
			}
			set
			{
				if ((this._SPEED != value))
				{
					this._SPEED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEGRAM", DbType="NChar(127)")]
		public string TELEGRAM
		{
			get
			{
				return this._TELEGRAM;
			}
			set
			{
				if ((this._TELEGRAM != value))
				{
					this._TELEGRAM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POWER", DbType="Int NOT NULL")]
		public int POWER
		{
			get
			{
				return this._POWER;
			}
			set
			{
				if ((this._POWER != value))
				{
					this._POWER = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
